config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'home/index'
  root 'home#index'

  namespace :admin do
    resources :blogs do
      resources :articles
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :blog
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end

app/models/blog.rb
class Blog < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_many :user_blog_interfaces
  has_many :users, through: :user_blog_interfaces

  # validations ...............................................................
  validates :name, presence: true
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  def user_names
    users.map(&:name)
  end
  # private instance methods ..................................................
end

app/models/user.rb
class User < ApplicationRecord
  # extends ...................................................................
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: {
    admin: 1,      # 最高權限管理員
    client: 2,     # 客戶
  }
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_many :user_blog_interfaces
  has_many :blogs, through: :user_blog_interfaces

  accepts_nested_attributes_for :blogs
  # validations ...............................................................
  validates :name, presence: true
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  attribute :role, :integer, default: 2
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end

app/models/user_blog_interface.rb
class UserBlogInterface < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :user
  belongs_to :blog
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end

app/controllers/admin/apps_controller.rb
class Admin::AppsController < Admin::BaseController
  def index; end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
  before_action :find_blog, only: [:new, :create, :edit, :destroy]
  before_action :find_article, only: [:edit, :update, :destroy]
  before_action :enable_access?, only: [:new, :edit]

  def new
    @article = @blog.articles.build
  end

  def create
    if @blog.articles.create(article_params)
      redirect_to admin_blog_path(@blog)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      redirect_to admin_blog_path(@article.blog)
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to admin_blog_path(@blog)
  end

  private

  def article_params
    params.require(:article).permit(:title, :context, :is_private)
  end

  def find_blog
    @blog = Blog.find(params[:blog_id])
  end

  def find_article
    @article = Article.find(params[:id])
  end

  def enable_access?
    render404 unless current_user.blog_ids.include?(@blog.id)
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'
  before_action :authenticate_user!

  def render404
    render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found
  end
end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < Admin::BaseController
  before_action :find_blog, only: [:show, :edit, :update, :destroy]
  before_action :enable_access?, only: [:show, :edit, :update, :destroy]

  helper_method :user_collect

  def index
    @blogs = current_user.blogs
  end

  def show
    @articles = @blog.articles
  end

  def new
    @blog = current_user.blogs.build
  end

  def create
    if current_user.blogs.create(blog_params)
      redirect_to admin_blogs_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @blog.update(blog_params)
      redirect_to admin_blogs_path
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to admin_blogs_path
  end

  def user_collect
    User.all.collect do |x|
      next if x.id == current_user.id

      [x.name, x.id]
    end.compact
  end

  private

  def blog_params
    params.require(:blog).permit(:name, user_ids: [])
  end

  def find_blog
    @blog = Blog.find(params[:id])
  end

  def enable_access?
    render404 unless current_user.blog_ids.include?(@blog.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(_resource)
    admin_blogs_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/articles/_form.html.erb
<%= form_with model: [:admin, :blog, article] do |form| %>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control", placeholder: "Article title" %>
  </div>

  <br>

  <div class="mb-3">
    <%= form.label :context, class: "form-label" %>
    <%= form.text_area :context, class: "form-control" %>
  </div>

  <br>

  <div class="mb-3 form-check">
    <%= form.label :is_private, '私有文章', class: "form-check-label" %>
    <%= form.check_box :is_private, class: "form-check-input" %>
  </div>

  <br>
  <%= form.submit class: "btn btn-primary" %>
  <%= link_to 'Back', url_for(:back), class: "btn btn-danger" %>
<% end %>

app/views/admin/articles/edit.html.erb
<div class="container">
  <h1>Edit the Article</h1>

  <%= render 'form', article: @article %>
</div>

app/views/admin/articles/new.html.erb
<div class="container">
  <h1>Create a new Article</h1>

  <%= render 'form', article: @article %>
</div>

app/views/admin/blogs/_form.html.erb
<%= form_with model: [:admin, blog] do |form| %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control", placeholder: "Blog name" %>
  </div>

  <% if current_user.admin? %>
    <br>
    <div class="mb-3">
      <%= form.label :user_ids, 'Users', class: "form-label" %>
      <%= form.select :user_ids, user_collect, {}, multiple: true, class: "form-select" %>
    </div>
  <% end %>

  <br>

  <%= form.submit class: "btn btn-primary" %>
  <%= link_to 'Back', url_for(:back), class: "btn btn-danger" %>
<% end %>

app/views/admin/blogs/edit.html.erb
<div class="container">
  <h1>Edit the Blog</h1>

  <%= render 'form', blog: @blog %>
</div>

app/views/admin/blogs/index.html.erb
<div class="container">
  <%= link_to '新增 Blog', new_admin_blog_path, class: 'btn btn-primary' %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Blog Name</th>
        <th scope="col">Users</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @blogs.each_with_index do |b, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= b.name %></td>
          <td><%= b.user_names %></td>
          <td>
            <%= link_to '查看所有文章', admin_blog_path(b) %>
            <%= link_to '編輯', edit_admin_blog_path(b) %>
            <%= link_to '刪除', admin_blog_path(b), method: :delete, data: {confirm: "Are you sure?"} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/blogs/new.html.erb
<div class="container">
  <h1>Create a new Blog</h1>

  <%= form_with model: [:admin, @blog] do |form| %>
    <%= form.text_field :name, placeholder: "Blog Name" %>
    <%= form.submit %>
  <% end %>
</div>

app/views/admin/blogs/show.html.erb
<div class="container">
  <%= link_to '新增文章', new_admin_blog_article_path(@blog), class: 'btn btn-primary' %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Article title</th>
        <th scope="col">私有文章</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @articles.each_with_index do |a, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= a.title %></td>
          <td><%= a.is_private? ? '是' : '否' %></td>
          <td>
            <%= link_to '編輯', edit_admin_blog_article_path(@blog, a) %>
            <%= link_to '刪除', admin_blog_article_path(@blog, a), method: :delete, data: {confirm: "Are you sure?"} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/home/index.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check" viewBox="0 0 16 16">
    <title>Check</title>
    <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
  </symbol>
</svg>

<div class="container py-3">
  <header>
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
        <span class="fs-4">DL work</span>
      </a>

      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <%= link_to '登入', admin_blogs_path, class: 'me-3 py-2 text-dark text-decoration-none' %>
        <%= link_to '註冊', new_user_registration_path, class: 'me-3 py-2 text-dark text-decoration-none' %>
      </nav>
    </div>

    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal">Pricing</h1>
      <p class="fs-5 text-muted">Quickly build an effective pricing table for your potential customers with this Bootstrap example. It’s built with default Bootstrap components and utilities with little customization.</p>
    </div>
  </header>

  <main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Free</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$0<small class="text-muted fw-light">/mo</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>10 users included</li>
              <li>2 GB of storage</li>
              <li>Email support</li>
              <li>Help center access</li>
            </ul>
            <button type="button" class="w-100 btn btn-lg btn-outline-primary">Sign up for free</button>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Pro</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$15<small class="text-muted fw-light">/mo</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>20 users included</li>
              <li>10 GB of storage</li>
              <li>Priority email support</li>
              <li>Help center access</li>
            </ul>
            <button type="button" class="w-100 btn btn-lg btn-primary">Get started</button>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm border-primary">
          <div class="card-header py-3 text-white bg-primary border-primary">
            <h4 class="my-0 fw-normal">Enterprise</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$29<small class="text-muted fw-light">/mo</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>30 users included</li>
              <li>15 GB of storage</li>
              <li>Phone and email support</li>
              <li>Help center access</li>
            </ul>
            <button type="button" class="w-100 btn btn-lg btn-primary">Contact us</button>
          </div>
        </div>
      </div>
    </div>

    <h2 class="display-6 text-center mb-4">Compare plans</h2>

    <div class="table-responsive">
      <table class="table text-center">
        <thead>
          <tr>
            <th style="width: 34%;"></th>
            <th style="width: 22%;">Free</th>
            <th style="width: 22%;">Pro</th>
            <th style="width: 22%;">Enterprise</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row" class="text-start">Public</th>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Private</th>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
        </tbody>

        <tbody>
          <tr>
            <th scope="row" class="text-start">Permissions</th>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Sharing</th>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Unlimited members</th>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Extra security</th>
            <td></td>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
        </tbody>
      </table>
    </div>
  </main>

  <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="../assets/brand/bootstrap-logo.svg" alt="" width="24" height="19">
        <small class="d-block mb-3 text-muted">&copy; 2017–2021</small>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Cool stuff</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Random feature</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team feature</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Stuff for developers</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Another one</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Last time</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Resource</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Resource name</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Another resource</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Final resource</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Locations</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Privacy</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Terms</a></li>
        </ul>
      </div>
    </div>
  </footer>
</div>

app/views/layouts/admin.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DlOperation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
          <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
            <a href="/admin/apps" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
              <span class="fs-5 d-none d-sm-inline">Menu</span>
            </a>
            <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
              <li class="nav-item">
                <a href="/admin/blogs" class="nav-link align-middle px-0">
                  <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Blogs</span>
                </a>
              </li>
              <!-- <li>
                <a href="#submenu3" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                  <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline">Products</span> </a>
                  <ul class="collapse nav flex-column ms-1" id="submenu3" data-bs-parent="#menu">
                  <li class="w-100">
                    <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 1</a>
                  </li>
                  <li>
                    <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 2</a>
                  </li>
                  <li>
                    <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 3</a>
                  </li>
                  <li>
                    <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 4</a>
                  </li>
                </ul>
              </li> -->
            </ul>
            <hr>
            <div class="dropdown pb-4">
              <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                <span class="d-none d-sm-inline mx-1"><%= current_user.name %></span>
              </a>
              <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                <!-- <li><a class="dropdown-item" href="#">New project...</a></li>
                <li><a class="dropdown-item" href="#">Settings</a></li>
                <li><a class="dropdown-item" href="#">Profile</a></li> -->
                <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
              </ul>
            </div>
          </div>
        </div>
        <div class="col py-3">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DlOperation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>